### ISSUE TITLE
Add --name to docker run command

### ISSUE THREAD

**Issue by abhayaman669** [abhayaman669/fastapi-psql-boilerplate#7]
Add `--name` to docker run command in `README.md`

**Comment by 96RadhikaJadhav** [comment]
@abhayaman669  Can I work on it?

**Comment by abhayaman669** [comment]
@96RadhikaJadhav yes you can work there are many more easy tasks if you want to contribute. 🙂

**Comment by abhayaman669** [comment]
thanks @96RadhikaJadhav
